insert into PRODUCTS (product_id, name, warehouse_id) values (1, 'Marsh Jaumea', 5);
insert into PRODUCTS (product_id, name, warehouse_id) values (2, 'Smallflower Phacelia', 5);
insert into PRODUCTS (product_id, name, warehouse_id) values (3, 'Parry''s Rabbitbrush', 1);
insert into PRODUCTS (product_id, name, warehouse_id) values (4, 'Sporopodium Lichen', 2);
insert into PRODUCTS (product_id, name, warehouse_id) values (5, 'Nellie Cory Cactus', 4);
insert into PRODUCTS (product_id, name, warehouse_id) values (6, 'Beard Lichen', 5);
insert into PRODUCTS (product_id, name, warehouse_id) values (7, 'Spectacular Flatsedge', 1);
insert into PRODUCTS (product_id, name, warehouse_id) values (8, 'Bentley''s Coralroot', 4);
insert into PRODUCTS (product_id, name, warehouse_id) values (9, 'Arctoa Moss', 5);
insert into PRODUCTS (product_id, name, warehouse_id) values (10, 'Foothill Sunburst', 2);
insert into PRODUCTS (product_id, name, warehouse_id) values (11, 'Agueweed', 2);
insert into PRODUCTS (product_id, name, warehouse_id) values (12, 'Guatemalan Avocado', 3);
insert into PRODUCTS (product_id, name, warehouse_id) values (13, 'Pringle''s Cudweed', 2);
insert into PRODUCTS (product_id, name, warehouse_id) values (14, 'Chia', 3);
insert into PRODUCTS (product_id, name, warehouse_id) values (15, 'Brickellbush', 3);
insert into PRODUCTS (product_id, name, warehouse_id) values (16, 'Javanese Flatsedge', 2);
insert into PRODUCTS (product_id, name, warehouse_id) values (17, 'Annual Muhly', 2);
insert into PRODUCTS (product_id, name, warehouse_id) values (18, 'Clokey''s Greasebush', 3);
insert into PRODUCTS (product_id, name, warehouse_id) values (19, 'Heartleaf Bittercress', 5);
insert into PRODUCTS (product_id, name, warehouse_id) values (20, 'Winged Sumac', 5);
insert into PRODUCTS (product_id, name, warehouse_id) values (21, 'Saltmarsh Sea Lavender', 2);
insert into PRODUCTS (product_id, name, warehouse_id) values (22, 'Disc Lichen', 4);
insert into PRODUCTS (product_id, name, warehouse_id) values (23, 'Melicgrass', 4);
insert into PRODUCTS (product_id, name, warehouse_id) values (24, 'Rim Lichen', 5);
insert into PRODUCTS (product_id, name, warehouse_id) values (25, 'Rough Hedgenettle', 5);
