insert into PRODUCTS (product_id, name, description, warehouse_id) values (1, 'Longstalk Cranesbill', 'Geranium columbinum L.', 2);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (2, 'Western Sunflower', 'Helianthus anomalus S.F. Blake', 4);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (3, 'Alpine Mirrorplant', 'Coprosma montana Hillebr.', 4);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (4, 'Florida Flatsedge', 'Cyperus floridanus Britton', 2);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (5, 'Thintail', 'Lepturus R. Br.', 1);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (6, 'Chinese Crab Apple', 'Malus hupehensis (Pamp.) Rehder', 2);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (7, 'Colorado Aletes', 'Aletes humilis J.M. Coult. & Rose', 1);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (8, 'Ohio Buckeye', 'Aesculus glabra Willd. var. glabra', 2);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (9, 'Tapertip Desertparsley', 'Lomatium attenuatum Evert', 5);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (10, 'Saussurea', 'Saussurea amara (L.) DC. var. glomerata (Poir.) Trautv.', 1);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (11, 'Garberia', 'Garberia heterophylla (W. Bartram) Merr. & F. Harper', 5);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (12, 'Cryptantha', 'Cryptantha gypsophila Reveal & C.R. Broome', 3);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (13, 'Little Floatingheart', 'Nymphoides cordata (Elliott) Fernald', 1);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (14, 'Baker''s Lupine', 'Lupinus bakeri Greene', 4);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (15, 'Allenrolfea', 'Allenrolfea Kuntze', 1);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (16, 'Bigelow''s False Willow', 'Baccharis bigelovii A. Gray', 1);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (17, 'Graphina Lichen', 'Graphina abaphoides (Nyl.) Müll. Arg.', 4);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (18, 'Common Chickweed', 'Stellaria media (L.) Vill.', 4);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (19, 'Firecracker Flower', 'Dichelostemma ida-maia (Alph. Wood) Greene', 4);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (20, 'Nipplebract Arrowhead', 'Sagittaria papillosa Buchenau', 1);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (21, 'Graphina Lichen', 'Graphina scolectis (Tuck.) Fink', 3);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (22, 'Sycamore', 'Platanus L.', 5);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (23, 'Drooping Tonguefern', 'Elaphoglossum herminieri (Bory & Fée) T. Moore', 2);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (24, 'Eggleaf Twayblade', 'Listera ovata (L.) R. Br.', 4);
insert into PRODUCTS (product_id, name, description, warehouse_id) values (25, 'Hairy Fimbry', 'Fimbristylis puberula (Michx.) Vahl', 1);
